pipeline:
  test-maven:
    image: maven:3.6.0-jdk-8-alpine
    commands: 
      - cd backend
      - mvn test
    when:
      branch: feature/development
      event: push

  notify-devs:
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: dev
      username: drone