version: '3'

services:

  postgresql:
    image: postgres:11.1
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: florian
      POSTGRES_PASSWORD: IbkS=&S
      POSTGRES_DB: volume
    ports:
    - "5432:5432"
    volumes:
    - ./backend/video/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-java:
    build: ./backend/server
    container_name: backend-java
    ports:
    - "8080:8080"